# Generated by Django 3.0.7 on 2021-03-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('link', models.URLField(max_length=124)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
